AuScope/AuScope-Portal-UI

- project/src/app/portal-core-ui/service/openlayermap/ol-map-object.ts
This fixes the problem of being unable to draw a bounding box on the map.
> AUS-3314 Import 'createBox' as a standalone function

- project/src/app/modalwindow/modalwindow.scss
- project/src/app/modalwindow/querier/customanalytic/nvcl/nvcl.datasetlist.component.html
- project/src/app/modalwindow/querier/customanalytic/tima/tima.component.html
**project/src/app/modalwindow/modalwindow.scss:**
Make sure borders around tabs have consistent colour.
Tabs were set too low, cutting into the box below.
**project/src/app/modalwindow/querier/customanalytic/nvcl/nvcl.datasetlist.component.html:**
Remove extraneous ">" from "Scalar" tabs
**project/src/app/modalwindow/querier/customanalytic/tima/tima.component.html:**
Ensure TIMA analytic's tabs aren't affected by these changes.
> AUS-3320 Fixes for NVCL Analytic tabs

- project/src/app/menupanel/common/infopanel/infopanel.component.html
- project/src/app/menupanel/common/infopanel/subpanel/subpanel.component.html
- project/src/app/menupanel/common/infopanel/subpanel/subpanel.component.ts
- Displays copyright information. if supplied
- Renamed labels of information fields to be a more correct representation
> AUS-3410 Improved support for metadata information in the "Info" panel

- project/src/app/menupanel/common/filterpanel/filterpanel.component.ts
Moved the code that gets polygon filter into UtilitiesService
> AUS 3445: Polygon BBOX filter ignores additional filter in GetFeatureInfo

- project/angular.json
- project/src/app/menupanel/common/filterpanel/filterpanel.component.ts
- project/src/app/services/wcustom/iris/cs-iris.service.ts
Style is similar to Auscope Portal, but the font rendering is different and pixel sizes are being interpreted slightly differently.
Wait until the auscope CSW has been serialized by the server before trying the IRIS layers.
> Aus 3524 cesium iris kml

- project/src/app/cesium-map/csmap.component.ts
When the map changes to/from 2D/3D or Columbus view it will reposition to centre on Australia.
> AUS-3570 - Reposition Map

- project/src/environments/config.ts
Problem layers now load in Firefox.
> Aus 3572 firefox styled map bug

- project/src/app/cesium-map/csmap.component.ts
- project/src/styles.scss
Use tile parms instead of whole view.
Changed font color of Querier component in .card .accordion-link
> AUS-3529 Added wmsGetfeatureinfo support.

- project/src/app/_globals.scss
- project/src/app/app.module.ts
- project/src/app/cesium-map/csmap.clipboard.component.html
- project/src/app/cesium-map/csmap.clipboard.component.ts
- project/src/app/cesium-map/csmap.component.scss
- project/src/app/cesium-map/csmap.component.ts
- project/src/app/menupanel/activelayers/activelayerspanel.component.html
- project/src/app/menupanel/activelayers/activelayerspanel.component.ts
- project/src/app/menupanel/clipboard/clipboard.component.html
- project/src/app/menupanel/clipboard/clipboard.component.ts
- project/src/app/menupanel/layerpanel/layerpanel.component.html
- project/src/app/menupanel/menupanel.scss
- project/src/app/toppanel/help-menu/help-menu.component.html
- project/src/app/toppanel/help-menu/help-menu.component.scss
- project/src/app/toppanel/help-menu/help-menu.component.spec.ts
- project/src/app/toppanel/help-menu/help-menu.component.ts
- project/src/index.htm
- project/src/styles.scss
A number of UI changes, mostly info components of "Menu" in sidebar now sits in a dropdown at the right of the topnav panel.
Also:
* Global SCSS variables declared for AuScope style guideline colours.
* Display lat/lon coordinates at mouse position.
* Move Polygon Filter to Active Layers (visible if layers are present).
> Move help menu

- project/src/app/cesium-map/csmap.component.ts
Fix CSW boundary map clicks not working.
> AUS-3591 Fix CSW map clicks

- project/src/app/menupanel/layerpanel/layerpanel.component.ts
Remove unnecessary code for layer progress issue solved in portal-core-ui-app.
Corresponding portal-core-ui-app pull request: https://github.com/AuScope/portal-core-ui-app/pull/28
> AUS-3618 Fix layer progress issue

- project/src/app/menupanel/cataloguesearch/cataloguesearch.component.html
- project/src/app/menupanel/cataloguesearch/cataloguesearch.component.scss
- project/src/app/menupanel/cataloguesearch/cataloguesearch.component.ts
- project/src/app/menupanel/cataloguesearch/cataloguesearch.service.ts
Next button won't appear if last page.
Previous button (renamed from Last due to that also meaning "final") won't appear if first page.
Fixed bug where page numbers kept getting added to dropdown list after every search.
> AUS-3602 Catalogue search buttons only appear when useful

- project/src/app/app.module.ts
- project/src/app/cesium-map/csmap.clipboard.component.css
- project/src/app/cesium-map/csmap.clipboard.component.html
- project/src/app/cesium-map/csmap.clipboard.component.ts
- project/src/app/cesium-map/csmap.component.ts
- project/src/app/cesium-map/csmap.zoom.component.html
- project/src/app/cesium-map/csmap.zoom.component.scss
- project/src/app/cesium-map/csmap.zoom.component.ts
- project/src/extension/svg/select.svg
- project/src/index.htm
Moved polygon filter to map, always remains visible. Toggled via new map button.
> Aus 3614 polygon filter remains

- project/src/app/cesium-map/csmap.component.ts
- project/src/app/cesium-map/custom-querier-handler/iris-querier-handler.service.ts
- project/src/environments/ref.ts
IRIS layers can now be clicked.
Dependent on corresponding AuScope-Portal-UI Pull Request: https://github.com/AuScope/portal-core-ui-app/pull/31
**AND**
AuScope-PortalAPI PR: https://github.com/AuScope/AuScope-Portal-API/pull/38
Test using Passive Seismic -> Seismology in Schools Network layer.
> AUS-3592 IRIS layers can now be clicked

- project/src/environments/config.ts
Fixes  AUS-3617: Curtin Layer server issues.
Layers now proxied to avoid CORS issues.
!!! 
Needs https://github.com/AuScope/portal-core/pull/391 for backend support
!!!
> Fixes  AUS-3617: Curtin Layer now proxied to avoid CORS issues

- project/src/app/menupanel/common/downloadpanel/downloadpanel.component.html
- project/src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
- project/src/environments/environment.au2.ts
- project/src/environments/environment.dev.ts
- project/src/environments/environment.prod.ts
- project/src/environments/environment.ts
Changes to support time parameters in WCS requests, and improvements to the WCS download form
> Aus 3598 Changes to support time parameters in WCS requests, and improvements to the WCS download form

- project/src/app/menupanel/activelayers/activelayerspanel.component.html
- project/src/app/menupanel/activelayers/activelayerspanel.component.ts
- project/src/app/menupanel/cataloguesearch/cataloguesearch.component.html
- project/src/app/menupanel/custompanel/custompanel.component.html
- project/src/app/menupanel/layerpanel/layerpanel.component.html
Fix AUS-3603: Logic corrected and generally better error communication
> Fix AUS-3603: Logic corrected and generally better error communication

- project/src/app/cesium-map/csmap.component.ts
- project/src/app/modalwindow/querier/customanalytic/nvcl/nvcl.datasetlist.component.html
- project/src/app/modalwindow/querier/querier.modal.component.html
- project/src/app/modalwindow/querier/querier.modal.component.ts
Added spinners to:
* User clicking point and features are loading.
* User selects feature and specific feature info is loading.
Added a "No results" message to clicks with no results that suggests zooming.
Fixed minor bug in nvcl datasetlist template.
> AUS-3626 Spinners on feature loading

- project/src/app/menupanel/common/infopanel/openlayermappreview/olmap.preview.component.ts
Clicking preview map in info panel will zoom map to selected extent.
> AUS-3609 Preview map click to zoom

- project/src/app/cesium-map/csmap.component.ts
- project/src/app/menupanel/common/filterpanel/filterpanel.component.html
- project/src/app/menupanel/common/filterpanel/filterpanel.component.ts
- project/src/app/modalwindow/querier/querier.modal.component.html
Remove unnecessary service instantiations at component level in FIlterPanelComponent.
Fix bug where clicking KML point says No Results... despite showing results for point.
> A few minor fixes

- project/src/app/menupanel/cataloguesearch/cataloguesearch.component.html
- project/src/app/menupanel/custompanel/custompanel.component.html
- project/src/app/menupanel/custompanel/custompanel.component.ts
Added spinners for custom and catalogue layer loading.
> AUS-3632 Catalogue and Custom load layer spinners

- project/src/app/menupanel/common/filterpanel/filterpanel.component.ts
Add a timeout for adding layers via the state URL fragment in order to give UI time to catch up.
> AUS-3634 Recursive Error

- package-lock.json
- package.json
- src/app/cesium-map/csmap.component.ts
- src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
- src/app/modalwindow/querier/querier.modal.component.html
- src/app/modalwindow/querier/querier.modal.component.ts
- src/environments/config.ts
* AusLAMP stations layer added.
* Fix issue of clicks not responding after clicking on WMS map layer nowhere near features.
* Fix issue of spinner activating on query dialog if accordion closed.
* Bump version of portal-core-ui.
> AUS-3725-AusLAMP-Layers

- src/app/menupanel/cataloguesearch/cataloguesearch.component.html
- src/app/menupanel/common/downloadpanel/downloadpanel.component.html
- src/app/menupanel/common/filterpanel/filterpanel.component.html
- src/app/menupanel/custompanel/custompanel.component.html
- src/app/menupanel/data-explorer/data-explorer.component.html
- src/app/menupanel/layerpanel/layerpanel.component.html
- src/app/menupanel/permanentlink/permanentlink.component.html
- src/app/modalwindow/querier/querier.modal.component.html
- src/app/toppanel/help-menu/help-menu.component.html
- src/index.htm
Added more tooltips:
HelpMenuComponent
Help and information
index.htm
Layers added to map // Active Layers
Select predefined layers // Featured Layers
Enter a custom WMS endpoint // Custom Layers
Search CSW services for records // Data Search
PermanentLinkComponent
Create a link preserving current map layers
LayerPanelComponent
Search layers // now disabled if no text entered in search box
Clear search
Select image/data layers
Remove layer from map
FilterPanelComponent
Remove filter // Button now removed if no filters present
Select time to display // WMS time dropdown
Display analytics
CustomPanelComponent
Add WMS service URL layer to map // button now disabled if no text entered in search box
DataExplorerComponent
Search records using any text
Search records by spatial bounds
Click …
> AUS-3374 Tooltips

- src/app/menupanel/common/filterpanel/filterpanel.component.html
- src/app/menupanel/common/filterpanel/filterpanel.component.ts
Will no longer display a "No Filters" message in the FilterPanel if the layer has a FilterPanel ToolbarComponent.
> AUS-3722 Remove GRACE "No Filters" FIlterPanel message

- src/environments/config.ts
Added GRACE layer to CSV supported downloads, downloads now work.
> AUS-3735 GRACE Downloads

- src/app/menupanel/data-explorer/data-explorer.component.ts
Keywords under Data Search are now sorted.
> AUS-3736 Sort Data Search Keywords

- package.json
- src/app/cesium-map/csmap.component.ts
* Use the WMS 1.3.0 layers' sldBody130 parameter on GetFeatureInfo requests as it will have had the lat,lng coordinates swapped to lng,lat.
> AUS-3744 Polygon filter clicks

- package-lock.json
- src/environments/config.ts
Fixes problem of Geoscience Australia reports having "This layer cannot be displayed" message
> AUS-3754 Fix for cannot display message in GA reports

- src/app/menupanel/common/filterpanel/filterpanel.component.ts
- src/environments/environment.ts
add those URLs which needs proxy in config file
> related issue AUS-3731

- .github/workflows/build-prod-release.yml
- src/environments/environment.prod-https.ts
* Added 2 new build inputs:
- build-image-name: the name of the build image
- env-file: the environment file to use.
* Added an environment.prod-https.ts file for building https enabled version of portal.
> AUS-3767 Enable HTTPS

- src/app/menupanel/common/infopanel/subpanel/subpanel.component.html
Display CSW funder organisation if present in record info.
> AUS-3683 Funder CSW info

- src/app/menupanel/custompanel/custompanel.component.html
- src/app/menupanel/custompanel/custompanel.component.ts
Fixed issue with WMS service URLS that contained parameters.
Fixed issue with Info panel not opening dialogs when selected from custom panel.
> AUS-3560 & AUS-3790

- src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
- src/app/modalwindow/modalwindow.scss
- src/app/modalwindow/querier/customanalytic/nvcl/nvcl.datasetlist.component.html
- src/app/modalwindow/querier/customanalytic/nvcl/nvcl.datasetlist.component.ts
Fix bug where NVCL analytics spinner was always visible beneath images.
Minor code cleanup in DownloadPanelComponent.
To test, refer to JIRA issue: https://jira.csiro.au/browse/AUS-3789
> AUS-3789 NVCL Analytics Spinner

- src/app/menupanel/common/filterpanel/filterpanel.component.ts
- src/app/menupanel/common/model/ui/uitabpanel.model.ts
- src/app/menupanel/layerpanel/layerpanel.component.html
- src/app/menupanel/layerpanel/layerpanel.component.ts
- src/environments/config.ts
Reduced GetCapabilities call for a layer to when the LayerPanel is expanded, and also added a config layer list to limit unnecessary GetCaps calls.
> AUS-3794 Reduce GetCaps calls on Firefox

- src/app/app.module.ts
- src/app/menupanel/common/downloadpanel/downloadpanel.component.html
- src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
- src/app/modalwindow/layeranalytic/nvcl/nvcl.tsgdownload.component.html
- src/app/modalwindow/layeranalytic/nvcl/nvcl.tsgdownload.component.ts
- src/app/modalwindow/layeranalytic/nvcl/saver.provider.ts
- src/app/modalwindow/layeranalytic/nvcl/tsgdownload.service.ts
- src/app/modalwindow/layeranalytic/nvcl/tsgdownload.ts
AUS-3796 Added one TSGFile progress bar and feedback status.
AUS-3795 Added alert for no TSG files in boundary.
> AUS-3796 Added one TSGFile progress bar and feedback status.

- src/app/menupanel/search/searchpanel.component.html
- src/app/menupanel/search/searchpanel.component.scss
- src/app/menupanel/search/searchpanel.component.ts
- src/styles.scss
* Search query escaping now handled at front end.
* Search bar resizes correctly when screen becomes a lot smaller.
* Stopped automatic sidebar scrolling on search bar Info and Remove Layer button presses.
> AUS-3824 AUS-3825 Search Fixes

- src/app/menupanel/common/filterpanel/filterpanel.component.html
- src/app/services/filter/filter.service.ts
Fix issue where single dates in the FilterPanel hadn't been updated to properly use new FilterService.
> AUS-3823 Aster Layer Date Fix

- src/app/cesium-map/csmap.clipboard.component.ts
- src/app/menupanel/common/downloadpanel/downloadpanel.component.html
- src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
- src/app/menupanel/layerpanel/layerpanel.component.html
- src/app/menupanel/layerpanel/layerpanel.component.ts
- src/app/menupanel/menupanel.scss
- src/styles.scss
* Overhaul of download panel to simplify downloading data.
* Bounds are cleared when the user switches layer panel tabs, opens a new layer panel, or draws a new bound in another layer.
> AUS-3827 Downloads

- src/app/menupanel/common/infopanel/subpanel/subpanel.component.ts
'&' character was not being prepended to existing parameters.
> AUS-3849 InfoPanel Fix for the InfoPanel Fix

- package.json
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
Added missing urlNeedProxy setting to au-portal-dev settings file.
> AUS-3844 Aster layer getCaps fix

- src/app/menupanel/layerpanel/layerpanel.component.ts
Prevent polygon from disappearing when user switched panels.
> AUS-3843 Stop Polygons Disappearing

- src/app/menupanel/common/filterpanel/filterpanel.component.html
- src/app/menupanel/common/filterpanel/filterpanel.component.scss
Fix date dropdown bug where dropdown would not move when filter panel opened.
> AUS-3871-Fix

- src/app/app.module.ts
- src/app/menupanel/common/downloadpanel/downloadpanel.component.html
- src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
- src/app/menupanel/layerpanel/layerpanel.component.html
- src/app/menupanel/layerpanel/layerpanel.component.ts
- src/app/services/bounds/bounds.service.ts
Prevent bounding boxes (and polygons) disappearing when new layer opened.
> AUS-3861 Persist bounds (and polygons) between layers

- src/app/menupanel/common/infopanel/subpanel/subpanel.component.ts
Simplified GetLegendGraphic requests to the layer default so as to match WMS previews in the InfoPanel.
> AUS-3881 InfoPanel Console Errors

- package.json
- src/app/app.module.ts
- src/app/menupanel/activelayers/activelayerspanel.component.html
- src/app/menupanel/activelayers/activelayerspanel.component.ts
- src/app/menupanel/cataloguesearch/cataloguesearch.component.ts
- src/app/menupanel/common/filterpanel/filterpanel.component.ts
- src/app/menupanel/common/infopanel/subpanel/subpanel.component.ts
- src/app/menupanel/custompanel/custompanel.component.ts
- src/app/menupanel/data-explorer-record/data-explorer-record.component.ts
- src/app/menupanel/layerpanel/layerpanel.component.ts
- src/app/menupanel/search/searchpanel.component.ts
- src/app/modalwindow/legend/legend.modal.component.html
- src/app/modalwindow/legend/legend.modal.component.scss
- src/app/modalwindow/legend/legend.modal.component.ts
- src/app/services/legend/legend-ui.service.ts
- src/styles.scss
Added ability to display styled layer legends on screen via draggable dialogs.
> AUS-3886 Map Legends

- src/app/menupanel/activelayers/activelayerspanel.component.ts
- src/app/services/legend/legend-ui.service.ts
Add ability to display static image legends from server if a file has been defined in layers.yaml.
> AUS-3890 Static Legends

- src/app/menupanel/activelayers/activelayerspanel.component.html
- src/app/menupanel/activelayers/activelayerspanel.component.ts
- src/app/menupanel/layerpanel/layerpanel.component.html
- src/app/menupanel/layerpanel/layerpanel.component.ts
Only show the opacity slider for a layer if it is supported.
> AUS-3888 Remove opacity slider for unsupported layers

- src/app/menupanel/layerpanel/layerpanel.component.html
- src/app/menupanel/layerpanel/layerpanel.component.scss
- src/app/menupanel/layerpanel/layerpanel.component.ts
- src/app/models/bookmark.model.ts
- src/app/models/user.model.ts
- src/app/portal/portal.component.html
- src/app/portal/portal.component.ts
- src/app/services/api/auscope-api.service.ts
- src/app/services/auth/auth.service.ts
- src/app/services/user/user-state.service.ts
- src/styles.scss
The user can now persist bookmarks (AUS-3896).
Fixed bug involving side panels not being able to be collapsed/expanded (AUS-3894).
> AUS-3896 and AUS-3894 Bookmarking Layers

- src/app/menupanel/layerpanel/layerpanel.component.html
- src/app/menupanel/layerpanel/layerpanel.component.ts
Restored polygon filter toggling functionality.
> AUS-3895 Restore polygon filter

- docker/.htaccess
- docker/000-default.conf
- docker/Dockerfile
Modify Apache conf and add .htaccess file for redirects on deployed servers.
> AUS-3907 Docker redirects

- src/app/app.component.ts
- src/app/menupanel/layerpanel/layerpanel.component.ts
- src/app/menupanel/login/login-menu.component.html
- src/app/menupanel/login/login-menu.component.ts
- src/app/portal/portal.component.html
- src/app/portal/portal.component.ts
- src/app/services/api/auscope-api.service.ts
- src/app/services/auth/auth.service.ts
- src/app/services/user/user-state.service.ts
UserStateService's user object now determines if a user is logged in.
Bookmarking endpoints now under /secure server path.
403 user/bookmarking errors will log out a user.
Auto featured layers expansion removed.
> AUS-3897-Logout-Timed-Out-User

- package.json
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/cesium-map/csmap.component.ts
- src/app/menupanel/common/filterpanel/filterpanel.component.html
- src/app/menupanel/common/filterpanel/filterpanel.component.ts
- src/app/menupanel/data-explorer-record/data-explorer-record.component.ts
- src/app/menupanel/layerpanel/layerpanel.component.ts
- src/app/menupanel/login/login-menu.component.html
- src/app/menupanel/login/login-menu.component.ts
- src/app/menupanel/permanentlink/permanentlink.component.html
- src/app/menupanel/permanentlink/permanentlink.component.ts
- src/app/modalwindow/confirm/confirm.modal.component.html
- src/app/modalwindow/confirm/confirm.modal.component.ts
- src/app/modalwindow/permanentlink/create-permanentlink.modal.component.html
- src/app/modalwindow/permanentlink/create-permanentlink.modal.component.scss
- src/app/modalwindow/permanentlink/create-permanentlink.modal.component.ts
- src/app/modalwindow/permanentlink/permenantlinks.modal.component.html
- src/app/modalwindow/permanentlink/permenantlinks.modal.component.scss
- src/app/modalwindow/permanentlink/permenantlinks.modal.component.ts
- src/app/models/permanentlink.model.ts
- src/app/models/user.model.ts
- src/app/portal/portal.component.ts
- src/app/services/api/auscope-api.service.ts
- src/app/services/user/user-state.service.ts
- src/environments/environment.au2.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod-https.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
PermanentLinks are now persisted/loaded via DB accessed through AuScope-Portal-API.
PermanentLinks can be managed (edited, deleted and loaded) by authenticated users via the User menu. Added a re-usable confirmation dialog.
> AUS-3906 States in DB

- package.json
- src/app/cesium-map/advanced/grace/grace-legend.component.ts
- src/app/cesium-map/csmap.component.ts
- src/app/menupanel/common/filterpanel/advance/advanced-filter.directive.ts
- src/app/menupanel/common/filterpanel/advance/grace/grace-advanced-filter.component.html
- src/app/menupanel/common/filterpanel/advance/grace/grace-advanced-filter.component.ts
- src/app/menupanel/common/filterpanel/filterpanel.component.ts
- src/app/services/wcustom/grace/grace.service.ts
Fixed issues with GRACE layers not loading states correctly when loading from permanent links.
> AUS-3918 GRACE permanent link loading

- src/app/menupanel/activelayers/activelayerspanel.component.html
Fixed legend button not appearing for layers without opacity slider if they have a static legend.
> AUS-3925 Legend button hidden for KML layers

- src/environments/environment.ts
Removed Natural Earth basemap due to lack of resolution.
> AUS-3920 Remove NaturalEarthII BaseMap

- src/app/modalwindow/modalwindow.scss
- src/app/modalwindow/querier/customanalytic/nvcl/nvcl.datasetlist.component.html
- src/app/modalwindow/querier/customanalytic/nvcl/nvcl.datasetlist.component.ts
Fixed empty "Scalar select" when the fist draw dialog.
AUS-3924 Fixed the show legend issue.
> AUS-3928 Fixed scalar tooltip issues.

- src/app/modalwindow/permanentlink/permenantlinks.modal.component.ts
Fix console error when user logs out after viewing states.
> AUS-3940 Console error when user logs out after viewing states

- src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
- src/environments/config.ts
Allow omitting gsmlp:shape property from WFS download filter.
> AUS-3837 datasetUrlSupportedLayer

- src/app/modalwindow/modalwindow.scss
- src/app/modalwindow/querier/customanalytic/nvcl/nvcl.datasetlist.component.ts
- src/app/modalwindow/querier/customanalytic/nvcl/nvcl.datasetlist.dialog.component.html
Changed NVCL scalar legend dialog from Material to ngx-bootstrap so it wouldn't be hidden under the parent dialog.
> AUS-3939 Hidden NVCL Legend

- src/app/menupanel/login/login-menu.component.html
Made logout button 100% width of menu panel so clicking anywhere on the row triggers it.
> AUS-3941 Logout button width

- src/app/menupanel/layerpanel/layerpanel.component.ts
- src/app/services/user/user-state.service.ts
Simplified bookmark logic to fix bookmark icon not showing as deleted when deleted immediately after adding.
Chained some methods to simplify them.
> AUS-3944 Bookmark icon not showing deleted

- src/app/menupanel/login/login.component.ts
- src/environments/environment.au2.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod-https.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
add extra configuration option for auth api calls
> add extra configuration option for auth api calls

- src/app/app.module.ts
- src/app/menupanel/common/infopanel/cesiummappreview/cesium.preview.component.ts
- src/app/menupanel/data-explorer/data-explorer.component.html
- src/app/menupanel/data-explorer/data-explorer.component.scss
- src/app/menupanel/data-explorer/data-explorer.component.ts
- src/app/menupanel/data-explorer/data-explorer.service.ts
- src/app/menupanel/data-explorer/data-model.ts
- src/app/modalwindow/registry/add-registry.component.scss
- src/app/modalwindow/registry/add-registry.modal.component.html
- src/app/modalwindow/registry/add-registry.modal.component.ts
Allow user to define a custom registry for faceted CSW searches.
https://jira.csiro.au/browse/AUS-3804
> AUS-3804 Add Registry

- src/app/cesium-map/csmap.component.ts
Remove Intersects filters from SLD_BODYs.
> AUS-3967 Polygon filter clicks

- src/app/cesium-map/csmap.component.ts
- src/app/menupanel/layerpanel/layerpanel.component.scss
Change sizes of opacity slider and remove ripple effect.
> AUS-3979 TMI Layers

- src/app/menupanel/portal-details-panel/portal-details-panel.component.html
- src/app/menupanel/portal-details-panel/portal-details-panel.component.scss
- src/app/menupanel/portal-details-panel/portal-details-panel.component.ts
- src/app/modalwindow/disclaimer/disclaimer.modal.component.html
- src/app/modalwindow/disclaimer/disclaimer.modal.component.scss
- src/app/modalwindow/disclaimer/disclaimer.modal.component.ts
Stop disclaimer window from immediately closing.
> AUS-3974 Stop disclaimer window closing immediately

- src/app/menupanel/layerpanel/layerpanel.component.scss
- src/environments/config.ts
Add AuScope MT Collection layers as CSW layers
Fix overlapping slider occluding rubbish bin icon
> Aus 4017 Add AuScope MT Collection layers as CSW layers

- src/app/cesium-map/csmap.component.ts
- src/app/modalwindow/querier/querier.modal.component.html
Fixed issue where user could be told there were no features after clicking even when there were features.
https://jira.csiro.au/browse/AUS-4068
> AUS-4068 Click to Zoom Error

- src/app/cesium-map/csmap.component.ts
- src/app/modalwindow/querier/querier.modal.component.ts
Modified how feature clicks are dealt with to remove downloading message error when no features are returned on a single layer.
> AUS-4083 Feature Click Error

- .github/workflows/azure-static-web-apps-thankful-flower-08081a31e.yml
- package-lock.json
- package.json
- src/app/menupanel/portal-details-panel/portal-details-panel.component.html
> Release 6.4.0

- package-lock.json
- package.json
- src/app/menupanel/common/infopanel/subpanel/subpanel.component.ts
- src/app/menupanel/data-explorer/data-explorer.service.ts
- src/app/menupanel/search/searchpanel.component.html
- src/app/menupanel/search/searchpanel.component.scss
- src/app/menupanel/search/searchpanel.component.ts
- src/app/modalwindow/disclaimer/confirm/confirm.modal.component.html
- src/app/modalwindow/disclaimer/confirm/confirm.modal.component.ts
- src/app/models/knownlayerandrecords.model.ts
- src/app/models/searchresponse.model.ts
- src/app/services/api/auscope-api.service.ts
- src/app/services/search/search.service.ts
Removed disk caching, all CSW records are now indexed with Elasticsearch.
Searching is via index, not CSW registries directly.
> AUS-4031 Elasticsearch CSW Search

- src/app/menupanel/search/searchpanel.component.html
- src/app/portal/portal.component.html
Move permanent link down a tad.
> Fix search reset.

- src/app/menupanel/portal-details-panel/portal-details-panel.component.html
- src/app/menupanel/portal-details-panel/portal-details-panel.component.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
- src/tsconfig.app.json
> show package version in UI

- src/app/menupanel/custompanel/custompanel.component.html
- src/app/menupanel/custompanel/layergroup.component.html
- src/app/menupanel/search/searchpanel.component.html
- src/app/menupanel/search/searchpanel.component.ts
- src/app/portal/portal.component.html
Custom layers functionality moved off the side bar to the right of the search bar.
> AUS-4104 Move Custom Layers to Searchbar

- src/app/menupanel/search/searchpanel.component.html
- src/app/menupanel/search/searchpanel.component.scss
Shift the search query clear text button to right.
> AUS-4121 Shift search query clear text button

- src/app/browsepanel/browsepanel.component.html
- src/app/browsepanel/browsepanel.component.scss
Changed cursor type and highlighted background colour on browse menu rows.
> AUS-4116 Brwose Menu Highlighting

- src/app/browsepanel/browsepanel.component.scss
Groups/layer text now changes font colour when hovering over column parent.
> AUS-4116 (again) - Highlighting

- src/app/menupanel/activelayers/activelayerspanel.component.html
- src/app/menupanel/activelayers/activelayerspanel.component.scss
- src/app/menupanel/activelayers/activelayerspanel.component.ts
- src/app/menupanel/common/downloadpanel/downloadpanel.component.html
- src/app/menupanel/common/filterpanel/filterpanel.component.html
- src/app/menupanel/menupanel.scss
- src/app/portal/portal.component.html
- src/styles.scss
Fix bug with misaligned active layers when more than one was present.
Changed drag button and behaviour.
Disabled some panels during drag.
Lots of other little UI tweaks here.
> AUS-4118-ActiveLayers-Alignment

- src/app/_globals.scss
- src/app/app.module.ts
- src/app/auscope-styles.scss
- src/app/browsepanel/browsepanel.component.html
- src/app/browsepanel/browsepanel.component.scss
- src/app/cesium-map/csmap.clipboard.component.scss
- src/app/cesium-map/csmap.component.scss
- src/app/cesium-map/csmap.component.ts
- src/app/cesium-map/csmap.split.component.scss
- src/app/cesium-map/csmap.zoom.component.scss
- src/app/cesium-map/csmap.zoom.component.ts
- src/app/menupanel/common/infopanel/subpanel/subpanel.component.html
- src/app/menupanel/login/login-menu.component.scss
- src/app/menupanel/menupanel.scss
- src/app/menupanel/permanentlink/permanentlink.component.scss
- src/app/menupanel/permanentlink/permanentlink.component.ts
- src/app/menupanel/search/searchpanel.component.html
- src/app/menupanel/search/searchpanel.component.scss
- src/app/menupanel/search/searchpanel.component.ts
- src/app/menupanel/toolbar/toolbar.component.html
- src/app/menupanel/toolbar/toolbar.component.scss
- src/app/menupanel/toolbar/toolbar.component.ts
- src/app/portal/portal.component.html
Info panel now displays next to search results provided room exists.
Search bar moved off header and onto map.
> AUS-4099 Search Bar Moved to Map and Contains Info Panel

- package-lock.json
- src/app/menupanel/common/downloadpanel/downloadpanel.component.html
- src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
- Uses the end date instead of trying to guess based on the start date
- Recalculates the start and end date based on the selected stations so users won't ask for values that don't exist
> AUS-4102 Fix end date bug in IRIS (seismic) downloads

- src/app/menupanel/common/infopanel/subpanel/subpanel.component.ts
Replaced the background preview map with one hosted on the Community Geoserver.
> AUS-4131 Replace Preview Map

- src/app/browsepanel/browsepanel.component.html
- src/app/browsepanel/browsepanel.component.scss
- src/app/menupanel/common/infopanel/subpanel/subpanel.component.html
- src/app/menupanel/menupanel.scss
- src/app/menupanel/search/searchpanel.component.html
- src/app/menupanel/search/searchpanel.component.scss
Have added scroll-bars to:
- Browse panel (groups and layers).
- Downloads panel.
Browse panel now won't extend beyond bottom of page.
> AUS-4143 Scroll bars (Browse/Downloads)

- src/app/menupanel/custompanel/custompanel.component.html
- src/app/menupanel/custompanel/custompanel.component.ts
- src/app/menupanel/menupanel.scss
- src/app/menupanel/search/searchpanel.component.html
- src/app/menupanel/search/searchpanel.component.scss
Modifications to Custom Layers:
* User can press ENTER to start search.
* Search button colour matches main UI buttons.
* Custom Layers pane won't exceed screen and scroll bars if too many results.
* Closing Custom Layers panel won't remove results.
> AUS-4144 Custom Layers Improvements

- src/app/menupanel/search/searchpanel.component.html
Fixed bug where Custom Layers panel was obscuring map clicks.
> AUS-4084 Map clicks under hidden Cistom Layers panel

- src/app/menupanel/common/infopanel/infopanel.component.html
- src/app/menupanel/common/infopanel/infopanel.component.scss
- src/app/menupanel/common/infopanel/infopanel.component.ts
Improvements to InfoPanel:
* Scrollbar offset removed.
* Panel only takes up as much room as it needs if no scrollable content.
> AUS-4148 InfoPanel Prettying

- src/app/menupanel/custompanel/custompanel.component.ts
Prevent custom WMS or KML layers being added to the list of available layers more than once.
> AUS-4146 Adding Custom Layer Multiple Times

- src/app/menupanel/search/searchpanel.component.scss
Increase z-index of search panel so it opens over browse panel.
> AUS-4155 Search Panel Opens Over Browse Panel

- src/app/menupanel/search/searchpanel.component.ts
Custom layers panel now collapses when user clicks outside it.
> AUS-4159 Custom Layers Panel Outside Click Collapse

- src/app/cesium-map/csmap.clipboard.component.html
Added a <rectangles-editor> editor component to the ac-map (via CsMapClipboardComponent).
> AUS-4163 Draw Bounds Broken

- src/app/cesium-map/advanced/grace/grace-legend.component.scss
- src/app/cesium-map/csmap.component.ts
- src/app/menupanel/common/filterpanel/advance/grace/grace-advanced-filter.component.scss
Moved GRACE legend so it doesn't appear over shifted map buttons.
Removed shading from GRACE filter panel.
> AUS-4158 GRACE Legend Placement

- src/app/browsepanel/browsepanel.component.scss
Shifted browse menu closer to browse button.
> AUS-4183 Move Browse Menu Up

- src/app/menupanel/activelayers/activelayerspanel.component.scss
- src/app/portal/portal.component.html
* Reduced the size of active layer panels when dragged.
* Removed hidden ngx-bootstrap dialogs from HTML to prevent them appearing when layers are dragged and scrollbar is visible.
> AUS-4161 Layer Re-Ordering Issue

- src/app/cesium-map/csmap.clipboard.component.html
- src/app/cesium-map/csmap.clipboard.component.scss
- src/app/menupanel/login/login-menu.component.html
- src/app/menupanel/login/login-menu.component.scss
* ROI icon colour on polygon clipboard made lighter.
* ROI menu text and icon colour made purple.
* Toggle button removed from polygon clipboard.
> AUS-4169-4176 ROI Colours

- package-lock.json
- src/app/modalwindow/modalwindow.scss
- src/app/modalwindow/querier/querier.modal.component.html
- src/app/modalwindow/querier/querier.modal.component.ts
- Improved UI scrolling
- Made the "X" icon to close the window larger
- Include HTML from KML and CSW record (report) layers
- Made "Image" "Scalar" etc. buttons disappear when not required rather than be disabled
> AUS-4189 Fixed problem of missing popup info upon map click

- src/app/menupanel/activelayers/activelayerspanel.component.html
- src/app/menupanel/common/downloadpanel/downloadpanel.component.html
- src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
Removed ability for user to download polygon regions for layers that do not support it.
> AUS-4172 Disable Polygon Downloads

- src/app/cesium-map/csmap.component.ts
- src/app/modalwindow/querier/querier.modal.component.html
- src/app/modalwindow/querier/querier.modal.component.scss
- src/app/modalwindow/querier/querier.modal.component.ts
Added feature info dialog messages:
* Downloading feature info.
* No features, zoom to improve accuracy.
* Select a feature (when more than one).
Will also auto-select the first feature if it's the only one.
> AUS-4191 Feature Info Messages

- src/app/menupanel/search/searchpanel.component.ts
Fixed opacity sliders for CSW layers
> AUS-4210 Fix opacity sliders for CSW layers

- src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
Polygon download button logic simplified.
> AUS-4198 Simplify Polygon Logic

- src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
- src/app/menupanel/common/filterpanel/filterpanel.component.ts
- src/app/menupanel/common/infopanel/subpanel/subpanel.component.html
- src/app/menupanel/common/infopanel/subpanel/subpanel.component.scss
- src/app/menupanel/common/infopanel/subpanel/subpanel.component.ts
- src/app/menupanel/search/searchpanel.component.ts
- src/app/services/filter/filter.service.ts
If info panel preview or legend images fail, the proxy will be appended and images will try to be loaded again.
> AUS-4187 Preview and Legend Proxy

- src/app/menupanel/custompanel/custompanel.component.html
- src/app/menupanel/custompanel/custompanel.component.scss
- src/app/menupanel/search/searchpanel.component.html
- src/app/modalwindow/querier/querier.modal.component.ts
Display a warning for custom layers when their GetCapabilities show they have Min/MaxScaleDenominator properties.
> AUS-4049 Custom Layers Zoom Issue

- src/app/menupanel/activelayers/activelayerspanel.component.ts
- src/app/services/legend/legend-ui.service.ts
- src/app/services/ui/layer-manager.service.ts
Fix issue with legend button disabling when user closes legend dialog with Escape key.
Minor code refactors.
> AUS-4225 Legend button disabling after escape key close

- src/app/menupanel/common/downloadpanel/downloadpanel.component.html
- src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
Fixed issue with Passive Seismic dataselect downloads unavailable.
> AUS-4232 Passive Seismic Dataselect DLs

- src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
Fixed console bbox error.
Simplified AusPASS errors to use status code.
> AUS-4061 AusPASS Errors

- src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
Fix issue with not all zipped data sending response information.
> AUS-4061-Fix

- .github/workflows/build-package.yml
- package-lock.json
- package.json
- src/app/services/ui/layer-manager.service.ts
Stop UILayerModels from being remove upon layer deletion.
> AUS-4258 UILayerModel Removal

- src/app/menupanel/permanentlink/permanentlink.component.ts
- src/app/menupanel/search/searchpanel.component.ts
- src/app/modalwindow/layeranalytic/nvcl/nvcl.boreholeanalytic.component.html
- src/app/modalwindow/layeranalytic/nvcl/nvcl.boreholeanalytic.component.ts
- src/app/modalwindow/querier/querier.modal.component.html
- src/app/modalwindow/querier/querier.modal.component.ts
- src/app/services/user/user-state.service.ts
Update portal state calls from NVCL component.
Code tidying.
> AUS-4325 Remove Obselete Calls

- src/app/modalwindow/layeranalytic/nvcl/nvcl.boreholeanalytic.component.html
- src/app/modalwindow/layeranalytic/nvcl/nvcl.boreholeanalytic.component.ts
Fixed bug where resizing textfield on NVCL modal doesn't work.
> AUS-4260-NVCL-Modal-Textfield-Issue

- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
Restored OpenStreetMap base layer.
> AUS-4173 Restore OpenStreetMap Base Layer

- src/app/modalwindow/layeranalytic/nvcl/nvcl.boreholeanalytic.component.html
- src/app/modalwindow/layeranalytic/nvcl/nvcl.boreholeanalytic.component.ts
- src/app/modalwindow/layeranalytic/nvcl/nvcl.boreholeanalytic.service.ts
download NVCLAnalyticalJob result as csv.
> AUS-4094 view NVCLAnalyticalJob on map.

- src/app/modalwindow/layeranalytic/nvcl/nvcl.boreholeanalytic.component.ts
Changed form default values.
Added QueryCountsumMax function.
> AUS-4285 Added countSum for AnalyticalJob of newAlgorithm.

- src/app/menupanel/search/searchpanel.component.scss
- src/app/menupanel/search/searchpanel.component.ts
Fix issue with search results opening when spatial search bbox is dragged or resized.
Hide overflow in search alert box.
> AUS-4315 Drag search bbox

- package-lock.json
- package.json
Update portal-core-ui to v6.5.44.
> Update portal-core-ui to v6.5.44.

- src/app/menupanel/common/infopanel/subpanel/subpanel.component.html
- src/app/menupanel/common/infopanel/subpanel/subpanel.component.scss
- src/app/menupanel/common/infopanel/subpanel/subpanel.component.ts
- src/app/menupanel/menupanel.scss
Fix issue with some legends not sizing properly in preview panels.
Also fixed issue with legend load spinner in wrong place.
> AUS-4316 Preview Legend Sizing

- src/app/menupanel/common/downloadpanel/downloadpanel.component.html
- src/app/menupanel/common/downloadpanel/downloadpanel.component.scss
Reduce padding on download panel bounds buttons for better panel fit.
> AUS-4460 Download Panel Bounds Buttons

- src/app/menupanel/common/filterpanel/filterpanel.component.ts
Reset filters when a layer is added.
> AUS-4259 Filter Reset

- src/app/lib/portal-core-ui/utility/utilities.service.ts
- src/app/menupanel/common/infopanel/infopanel.component.html
- src/app/menupanel/common/infopanel/infopanel.component.scss
- src/app/menupanel/common/infopanel/infopanel.component.ts
- src/app/modalwindow/layeranalytic/nvcl/nvcl.boreholeanalytic.component.css
- src/app/modalwindow/layeranalytic/nvcl/nvcl.boreholeanalytic.component.html
- src/app/modalwindow/layeranalytic/nvcl/nvcl.tsgdownload.component.ts
- src/app/modalwindow/legend/legend.modal.component.html
- src/app/modalwindow/legend/legend.modal.component.scss
- src/app/modalwindow/querier/customanalytic/grace/grace-graph.modal.component.html
- src/app/modalwindow/querier/customanalytic/grace/grace-graph.modal.component.scss
- src/app/modalwindow/querier/customanalytic/nvcl/nvcl.datasetlist.component.scss
- src/app/modalwindow/querier/customanalytic/nvcl/nvcl.datasetlist.dialog.component.html
- src/app/modalwindow/querier/customanalytic/nvcl/nvcl.legend.html
- src/app/modalwindow/querier/querier.modal.component.html
- src/app/modalwindow/querier/querier.modal.component.scss
* Limited modal drag handles to modal headers.
* Added move cursor to modal headers.
* Fixed bug with NVCL Image Legend button disappearing when scalar was selected.
> AUS-4467 Limit modal drag handles to modal header
