AuScope/AuScope-Portal-UI

project/src/app/menupanel/cataloguesearch/cataloguesearch.component.html
project/src/app/menupanel/common/downloadpanel/downloadpanel.component.html

The display of bounding box coordinates were written for old version of Bootstrap and were not visible.

AUS-3315 Fix for invisible bounding box coordinates

---

project/src/app/menupanel/cataloguesearch/cataloguesearch.service.ts

Bbox west param was specified twice and overwrote the keyword value.

AUS-3368: CSW search by keyword with bbox select doesn't work

---

project/src/app/modalwindow/querier/querier.modal.component.html
project/src/app/modalwindow/querier/querier.modal.component.ts

- Created transformToHtml() method to call the WMSController to do the xslt conversion.
- If no transformation has been applied, it will then call the old parseTree() method (to display XML tree). 
- I removed most of the formatting I previously did in formatLabels(), as they're now done in the XSLT.

AUS-3286: transform WFS output to HTML if defined in XSLT

---

project/src/app/cesium-map/csmap.component.css
project/src/app/cesium-map/csmap.component.ts
project/src/app/cesium-map/csmap.split.component.scss
project/src/app/menupanel/layerpanel/layerpanel.component.html
project/src/app/menupanel/menupanel.scss

Adjust z-indices to prevent split panel bar from appearing on top of other components (Cesium widget toolbar, the custom widget split, NVCL dialogs etc).
Adjusted split colouring for slightly better visibility against imagery background.
Jira:  https://jira.csiro.au/browse/AUS-3575

Fix split z-indices issue

---

project/src/app/cesium-map/csmap.clipboard.component.css
project/src/app/cesium-map/csmap.clipboard.component.html
project/src/app/cesium-map/csmap.clipboard.component.ts
project/src/app/cesium-map/csmap.component.css

Make icons larger
Make all text the same black colour
Ensure that the buttons on the clipboard do not move up and down when a polygon name is added or removed
Use the AuScope dark jade colour as a background
Clipboard uses its own CSS file to ensure there are no conflicts with other components

AUS-3581 Fix and restyle truncated polygon clipboard

---

project/src/app/menupanel/layerpanel/layerpanel.component.ts

Timeout required before resetting layer in RenderStatusService as updateComplete was being called after and messing with the percentage completion.

AUS-3577 Layer loading bar not resetting

---

project/src/app/cesium-map/csmap.component.ts
project/src/app/menupanel/activelayers/activelayerspanel.component.html
project/src/app/menupanel/activelayers/activelayerspanel.component.ts
project/src/app/menupanel/layerpanel/layerpanel.component.html
project/src/app/menupanel/layerpanel/layerpanel.component.ts
project/src/app/menupanel/menupanel.scss

Only WMS layers have split direction buttons (when the split map is shown).
Removing a layer now properly resets its ImagerySplitDirection property.
Test:
* Add a WMS layer.
* Enable split map.
* Change the direction of the layer to Left or Right.
* Delete the layer.
* Re-add the layer, the split direction should have reset to Both (was originally remaining as Left or Right).
* To test only WMS layers prompting map split buttons, also try adding a CSW layer (e.g. Models). No buttons should appear.

AUS-3601 Split map fix

---

project/src/app/menupanel/common/filterpanel/filterpanel.component.html
project/src/app/menupanel/common/filterpanel/filterpanel.component.scss
project/src/app/menupanel/common/filterpanel/filterpanel.component.ts

Will only show the Add Layer button if the layer is supported, otherwise a brief message will explain why the layer can't be added and show the list of supporting layers.
Requires corresponding portal-core-ui-app pull request: https://github.com/AuScope/portal-core-ui-app/pull/29

AUS-3599-Add-Layers-Only-When-Can

---

project/src/app/menupanel/common/filterpanel/filterpanel.component.ts

Ignore filters that have no value, or in the case of the Provider filters where all values are false.
Note that there's still an issue with Provider filter not filtering properly but that's a separate issue currently being worked on.

AUS-3619 - Ignore empty filters

---

project/src/app/cesium-map/csmap.clipboard.component.html
project/src/app/cesium-map/csmap.clipboard.component.scss
project/src/app/cesium-map/csmap.clipboard.component.ts
project/src/app/cesium-map/csmap.component.ts
project/src/app/menupanel/common/filterpanel/filterpanel.component.ts
project/src/app/menupanel/layerpanel/layerpanel.component.html
project/src/app/menupanel/layerpanel/layerpanel.component.ts
project/src/app/menupanel/menupanel.scss
project/src/app/modalwindow/querier/querier.modal.component.ts
project/src/environments/config.ts
project/src/environments/ref.ts

Added a message to layer panel saying polygon filter layers have been toggled and a button to clear toggle.
Get name of polygon to display in clipboard from polygon object. 
Filter layers are now determined by the presence of a BBOX filter instead of a config setting.
Enable/disable polygon filter buttons depending on state.
Fixed bug where clearing an applied polygon then re-adding layer would still filter to polygon.
All searches now check if polygon layers have been filtered and will only show those layers if they have.
All searches now expand layer groups that contain results to display layers.

Aus 3621 remove polygon filter context menu

---

project/src/app/modalwindow/querier/querier.modal.component.ts

Clear the current clipboard poly if the user adds one from the querier dialog.

AUS-3627 Remove user drawn poly if user selects one from Geol Provinces

---

src/environments/config.ts

This fixes the problem of popup windows not appearing for map clicks on 'GA/NCI National Geophysical Compilations' layer

AUS-3753 Enable JSON popups for 'GA/NCI National Geophysical Compilations'

---

src/app/menupanel/layerpanel/layerpanel.component.html
src/app/menupanel/layerpanel/layerpanel.component.ts

Stop Firefox from calling GetCaps for every layer despite whether they are showing or not.

AUS-3763 Firefox GetCaps issue

---

src/app/menupanel/activelayers/activelayerspanel.component.ts

When deleting a layer via Active Layers, any AdvancedMapComponents belonging to the layer will now be removed.

AUS-3776 Remove AdvancedMapComponents

---

src/app/cesium-map/csmap.component.ts

Fixed error where layers with OnlineResources of type "Unsupported" were showing server errors in the feature dialog when clicked due to the click handler taking the first OnlineResource rather than specifically asking for the WMS one.

AUS-3793 Unsupported Type Click Error

---

src/app/menupanel/common/infopanel/subpanel/subpanel.component.html
src/app/menupanel/common/infopanel/subpanel/subpanel.component.ts

Fix WMS URLs having a repeated service parameter and WFS URLs having a WMS service parameter.

AUS-3836 Fix InfoPanel URLs

---

src/app/menupanel/common/filterpanel/advance/grace/grace-advanced-filter.component.scss
src/app/menupanel/common/filterpanel/filterpanel.component.html
src/app/menupanel/common/filterpanel/filterpanel.component.scss
src/app/menupanel/layerpanel/layerpanel.component.html
src/app/menupanel/layerpanel/layerpanel.component.scss
src/app/menupanel/layerpanel/layerpanel.component.ts

Small UI fixes:
* Filter panel shifted right a tiny amount so it’s not on the edge of the screen.
* A little less padding at bottom of filter panel.
* Filter panel title width reduced so top panel border line comes closer to title.
* Filter panel left/right margins reduced so it aligns with the tab panel.
* Info button using Bootstrap L&F.
* Add layer button shifted slightly to align with (new) filter panel right edge.
* Added filter divider made light grey so it’s visible and hidden if no filters have been added.
* A tad less room under Add Layer button.
* Adjusted filter notification so it aligns with slightly wider filter panel.
* GRACE panel adjustments to match above.

AUS-3871 Filter/Layer panel UI tweaks

---

src/app/menupanel/data-explorer/data-explorer.component.html
src/app/menupanel/data-explorer/data-explorer.component.scss
src/app/menupanel/data-explorer/data-explorer.component.ts
src/app/menupanel/data-explorer/data-explorer.service.ts
yarn.lock

In order to reduce calls to CSW registries, the data search panel will no longer be populated with a full registry search by default, the user will now need to click the search button to initiate a search.

AUS-3875 Remove default data search

---

package.json
src/app/app.module.ts
src/app/cesium-map/csmap.component.ts
src/app/menupanel/activelayers/activelayerspanel.component.html
src/app/menupanel/activelayers/activelayerspanel.component.scss
src/app/menupanel/activelayers/activelayerspanel.component.ts
src/app/menupanel/cataloguesearch/cataloguesearch.component.ts
src/app/menupanel/clipboard/clipboard.component.ts
src/app/menupanel/common/filterpanel/filterpanel.component.ts
src/app/menupanel/common/model/ui/uilayer.model.ts
src/app/menupanel/custompanel/layergroup.component.ts
src/app/menupanel/data-explorer-record/data-explorer-record.component.html
src/app/menupanel/data-explorer-record/data-explorer-record.component.ts
src/app/menupanel/layerpanel/layerpanel.component.ts
src/app/menupanel/search/searchpanel.component.ts
src/app/services/ui/layer-manager.service.ts
src/app/services/user/user-state.service.ts

Allow layer reordering with drag and drop in the ActiveLayersPanel.
Layer order is now preserved in states and layers should load in the same order they were saved.
Adding/removing layers pushed to a new LayerManagerService class so code is consistent wherever this happens.
Layers that are re-added are pushed to the top of the ActiveLayers list so layer order is maintained.

AUS-3917 Layer Reordering

---

src/app/menupanel/common/downloadpanel/downloadpanel.component.ts
src/app/menupanel/login/login-menu.component.html
src/app/modalwindow/querier/customanalytic/nvcl/nvcl.datasetlist.component.ts
src/app/modalwindow/querier/querier.modal.component.html
src/app/modalwindow/querier/querier.modal.component.ts

- Fixed issue where pressing the Clear Bounds button on the download panel would clear all the download options from the download panel (e.g. Aster layers, refer to https://jira.csiro.au/browse/AUS-3936).
- Features on the QuerierModal component that do not have a node name no longer show a ":" character (e.g. "Mine View : <blank>").
- Node names now also look for the XML element "gml:NAME", so Geological Provinces names should now appear in the QuerierModal window.
- A few NVCL functions are now returned to prevent errors when required information is not present.

AUS-3936 Clear bounds issue, plus minor UI tweaks

---

src/app/app-routing.module.ts

This was already happening for index.html routes, but older states may use index.htm.

Redirect any states that have index.htm in their URL to root.

---

src/app/menupanel/activelayers/activelayerspanel.component.html
src/app/menupanel/activelayers/activelayerspanel.component.scss
src/app/menupanel/activelayers/activelayerspanel.component.ts
src/app/menupanel/layerpanel/layerpanel.component.html
src/app/menupanel/layerpanel/layerpanel.component.ts
src/app/menupanel/menupanel.scss
src/styles.scss

Fixed:
* Layout problem in Active Layers panel where components were being pushed off the right of the panel (AUS-3953).
* Layout problem in Featured Layers where long named layers could put the delete button in a position where it couldn't be pushed (AUS-3935).
* Opacity slider not updating as it was moved, only when it finished dragging. Also some style changes to slider.

AUS-3935-3947-3953 UI Issues

---

src/app/menupanel/common/filterpanel/advance/grace/grace-advanced-filter.component.ts
src/app/services/ui/layer-manager.service.ts

Fixed issue with state values not being persisted for GRACE layer.
Fixed bug where adding a state twice would remove it from the ManageStateService's stored state.

AUS-3942 GRACE state load values

---

src/main.ts

google analytics was starting up before the context had been loaded.  This caused the ga keys entered via the context file to be ignored.  So, I moved the GA init step and enableprodmode to run after the context load.

load context before google analytics

---

src/app/browsepanel/browsepanel.component.html
src/app/menupanel/common/infopanel/infopanel.component.html
src/app/menupanel/common/infopanel/subpanel/subpanel.component.html

Fixed bug with displaced previews on InfoPanel dialogs.
Reduced space between services on the InfoPanel via the browse menu.

AUS-4113 and AUS-4115 InfoPanel Adjustments

---

src/app/browsepanel/browsepanel.component.html
src/app/browsepanel/browsepanel.component.scss

The relevant browse menu panels will not display when groups and/or layers aren't selected.

Hide Browse Menu Panels

---

src/app/browsepanel/browsepanel.component.scss

The browse menu panel is now justified to the left of the map and will move with the sidebar.
Browse menu moved closer to the browse button.

AUS-4128 Browse Menu Positioning

---

src/app/menupanel/activelayers/activelayerspanel.component.ts

Active layers panel no longer expects every layer to be associated with a group.

AUS-4122 Custom Layers Bug

---

src/app/menupanel/search/searchpanel.component.html

Hiding KML panel means it still takes up space and pushed search results down, have re-ordered.

AUS-4144 Custom Layer Improvements (Quick Fix)

---

src/app/menupanel/login/login-menu.component.ts
src/app/menupanel/permanentlink/permanentlink.component.html
src/app/menupanel/permanentlink/permanentlink.component.ts
src/app/modalwindow/permanentlink/permanentlinks.modal.component.html

Permanent link button now immediately opens proper menu when user is logged in.
Permanent Link menu limited in size so that it doesn't go beyond the screen and the X and close buttons are always visible.

AUS-4149 Permanent Link Improvements

---

src/app/browsepanel/browsepanel.component.scss
src/app/menupanel/search/searchpanel.component.scss

Adjusted z-indices of search panel to allow help menu to display over it. Also adjusted browse menu to match so search will continue to open over that.

AUS-4156 Help Menu Obscured

---

src/app/browsepanel/browsepanel.component.ts

The check (is the user logged in) to see if the bookmarks checkbox should be displayed will now set the show bookmarks only flag to false if the user is logged out in order to stop all layers disappearing if the flag is true when the user logs out.

AUS-4174 Bookmarks and User Logging Out Issue

---

src/app/menupanel/activelayers/activelayerspanel.component.html
src/app/menupanel/activelayers/activelayerspanel.component.scss

If a single word in a custom layer is too long it will end with ellipses.
Added layer name as tooltip to active layers title.

AUS-4168 Custom Layer Names Too Long

---

src/app/menupanel/activelayers/activelayerspanel.component.scss

Active layer names will only occupy a single row and use ellipses to indicate truncation.

AUS-4204 Active Layer Names on Single Row

---

src/app/browsepanel/browsepanel.component.ts

Only use first times response in subscription to prevent addLayer firing unintentionally later

AUS-3883 Tasmanian Layer Zoom

---

src/app/menupanel/common/infopanel/subpanel/subpanel.component.ts

Prevent layers with world bounds from being modified when the preview is displayed.

Release - World Bounds Fix

---

src/app/menupanel/common/infopanel/subpanel/subpanel.component.ts

Prevent world-wide layers from being cropped to Australia when added to map after preview has been shown.

AUS-4229 World Map Bounds Cropping

---

src/app/menupanel/search/searchpanel.component.ts

Fixed error where de-selecting Restrict Spatial Bounds search option would not stop bounds restriction.

AUS-4221 Restrict Spatial Bounds

---

src/app/menupanel/common/downloadpanel/downloadpanel.component.html
src/app/menupanel/common/downloadpanel/downloadpanel.component.ts

Fix issue with Passive Seismic dataselect downloads being unavailable.

Release - Passive Seismic Dataselect DLs Fix

---

src/app/menupanel/search/searchpanel.component.ts
src/app/modalwindow/querier/customanalytic/nvcl/nvcl.datasetlist.component.ts

Update search service names, allow multiple to be added to search filter.

AUS-4297 Search Filter Issues

---

src/styles.scss

Reduce legend modals' z-index by 1 so as not to obscure browse/search panels.

AUS-4313 Recuce legend modal z-index

---

src/app/cesium-map/csmap.component.ts
src/app/menupanel/activelayers/activelayerspanel.component.html

AUS-4409: Fixed issue of Info button not appearing in Active Layers panel for CSW record layers (blue bbox only).
AUS-4410: Fixed issue of "Full Metadata and Download" links opening in same window.

AUS-4409 and AUS-4410 Missing Info button and link opening in same page
